### ISSUE TITLE
Cannot install. This integration does not support configuration via the UI

### ISSUE THREAD

**Issue by Pakawat75** [shenxn/ha-dyson-cloud#12]
Here is image when try to set up
![image](https://user-images.githubusercontent.com/80138215/162589542-3e6e0209-e751-4020-8760-c392a7e395b4.png)

**Comment by netmanchris** [comment]
Also seeing this error.

**Comment by kastrom** [comment]
I had the same issue. I fixed by removing the integrations via HACS, restarting, installing again in the order `ha-dyson` and then `ha-dyson-cloud`, then doing this all again. Afraid I have no idea which part of this witchcraft actually solved the issue.

**Comment by AnthonyBe** [comment]
Seeing same issue and am now on HA 2022.4.3

Tried @kastrom directions above but still seeing the same.

**Comment by kastrom** [comment]
@AnthonyBe if you're using one of the Home Assistant apps, try resetting the frontend cache after uninstalling, and then again after reinstalling `ha-dyson`.

Also `ha-dyson-cloud` seems to refer to an old version of `libdyson` and can interfere with the installation, so shouldn't be installed. See this thread for more details: https://github.com/shenxn/libdyson/issues/15#issuecomment-1094263191

**Comment by jb123567** [comment]
Getting the same error here. Have tried the workaround with no luck.

**Comment by gmcaesar** [comment]
getting same error messag

found this in the log

`Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 10:01:42 PM (3 occurrences)
Last logged: 10:02:08 PM

Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)
Error occurred loading configuration flow for integration dyson_local: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)`

**Comment by Guy-Falkes** [comment]
Somehow my integration stopped working. After several attempts at reconnecting i decided to reinstall the integration and now I'm seeing this exact samen error (that's why i came here/found this thread)....

**Comment by gmcaesar** [comment]
Is there any word on this being addressed, right now can't use the integration cause I can't add it to the system

**Comment by jb123567** [comment]
Mine installed after the upgrade to 2022.6.7, not sure why!

**Comment by AnthonyBe** [comment]
> Mine installed after the upgrade to 2022.6.7, not sure why!

I just tried again as I'm running HA 2022.6.7 (install HACS repo for Dyson Cloud v0.15.0, restart HA, add 'Dyson Cloud' integration) and got same error as in the original post in this thread:

`This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.`

Logged error:
`2022-06-27 21:07:24 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)`

**Comment by jubjub03** [comment]
I’ve also been getting the same error. Tried all the same remove, install, restart HA.

Anyone else having better luck?

**Comment by jubjub03** [comment]
> Mine installed after the upgrade to 2022.6.7, not sure why!

Were you getting the same error previously on an older version? Or was this first attempt?

**Comment by jb123567** [comment]
> > Mine installed after the upgrade to 2022.6.7, not sure why!
> 
> 
> 
> Were you getting the same error previously on an older version? Or was this first attempt?

Yeah, was having the issue on 2022.6.5, but seemed fine once on .7.

**Comment by Guy-Falkes** [comment]
> > > Mine installed after the upgrade to 2022.6.7, not sure why!
> > 
> > 
> > Were you getting the same error previously on an older version? Or was this first attempt?
> 
> Yeah, was having the issue on 2022.6.5, but seemed fine once on .7.

Really??? Lucky you! I upgraded to 2022.6.7 and tried it again but still the same error message...

**Comment by jubjub03** [comment]
Is there anyway to get support on this? I'm really keen to get it working. Is there any logs I can provide for someone to diagnose?

**Comment by gmcaesar** [comment]
i think this project has been abandoned,,,, there hasn't been any activity on it for over a year

**Comment by NicolasRigo** [comment]
Same here. It's too bad! It means no way to manage Dyson devices from HA anymore.

**Comment by haddood** [comment]
same issue Hass 2022.8.6

**Comment by maarten682** [comment]
Had this exact issue on a new setup (fan bought today, installed everything fresh). First thing i did was update my home assistant installation, didnt change anything. Then i removed the integrations completely from HACS, did a restart and reinstall and presto. All works fine.

Home Assistant 2022.8.6 - Supervisor 2022.08.3 - Operating System 8.5 - Frontend 20220802.0 - latest - Pi3
Dyson TP04/438 on current firmware as of aug 25 2022

**Comment by gmcaesar** [comment]
I'm still seeing the same issue and I did a remove of both local and cloud in haces reboot add local reboot add cloud reboot try to add and nothing work 

 Home Assistant 2022.8.7 Supervisor 2022.08.3 Operating System 8.5 Frontend 20220802.0 - latest

**Comment by maarten682** [comment]
Might want to give it a couple tries in different order, there could be some weirdness playing a part here. Once you get it going it does work so everything is still functional.

**Comment by gmcaesar** [comment]
tried a few diffrent orders and it didn't work, but deeper in the log found these errors:

2022-08-25 15:07:58.543 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)
2022-08-25 15:08:09.708 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration dyson_local: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)

**Comment by julet85** [comment]
@shenxn Any updates on this issue? It's been a couple of months now and those who are using the newer purifiers without the wifi sticker  are unable to use the integration. Thanks in advanced!
